### ISSUE TITLE
Attribute could not be set

### ISSUE THREAD

**Issue by baverozceylan** [imec-idlab/ns-3-dev-git#1]
When I tried to run lorawan-example.cc file, I get following error message;

"Attribute name=NbRep could not be set for this object: tid=ns3::LoRaWANNetDevice"

I think the program tries to set the NbReb attribute to an invalid value. 

How can I fix that ?

Baver

**Comment by fvdnabee** [comment]
Note that lorawan-example-tracing was primarily used during the final de of the module. The other examples are older. That said, you could try setting nbrep via lorawanhelper:
lorawanHelper.SetNbRep (1);

By default, lorawan-example doesn't touch nbrep though. So most likely you are experiencing a bug.  I don't have access to a computer to troubleshoot however(posting this from mobile).

**Comment by ejschiller** [comment]
Dear all,

I confirm that the bug exists:

https://github.com/imec-idlab/ns-3-dev-git.git in the lorawan branch, commit 0b80ed111ea64c8f473366500534a02ff4d9b284, I run the following:

./waf --run=lorawan-example
Waf: Entering directory `/home/ubuntu/ns-lorawan/ns-3-dev-git/build'
Waf: Leaving directory `/home/ubuntu/ns-lorawan/ns-3-dev-git/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (2.928s)
LoRaWANEndDeviceApplication::GetTypeId: ns3::UniformRandomVariable[Min=0|Max=6]
msg="Attribute name=NbRep could not be set for this object: tid=ns3::LoRaWANNetDevice", file=../src/core/model/object-base.cc, line=207
terminate called without an active exception
Command ['/home/ubuntu/ns-lorawan/ns-3-dev-git/build/src/lorawan/examples/ns3-dev-lorawan-example-debug'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

gdb build/src/lorawan/examples/ns3-dev-lorawan-example-debug
Reading symbols from /home/ubuntu/ns-lorawan/ns-3-dev-git/build/src/lorawan/examples/ns3-dev-lorawan-example-debug...done.
(gdb) r
Starting program: /home/ubuntu/ns-lorawan/ns-3-dev-git/build/src/lorawan/examples/ns3-dev-lorawan-example-debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
LoRaWANEndDeviceApplication::GetTypeId: ns3::UniformRandomVariable[Min=0|Max=6]
msg="Attribute name=NbRep could not be set for this object: tid=ns3::LoRaWANNetDevice", file=../src/core/model/object-base.cc, line=207
terminate called without an active exception

Program received signal SIGABRT, Aborted.
0x00007ffff0b35428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff0b35428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff0b3702a in __GI_abort () at abort.c:89
#2  0x00007ffff169584d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff16936b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff1693701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff4e6e91d in ns3::ObjectBase::SetAttribute (this=0x6711f0, name="NbRep", value=...)
    at ../src/core/model/object-base.cc:207
#6  0x00007ffff7b936bb in ns3::LoRaWANHelper::Install (this=0x7fffffffd950, c=...)
    at ../src/lorawan/helper/lorawan-helper.cc:123
#7  0x000000000040a5af in main (argc=1, argv=0x7fffffffde98) at ../src/lorawan/examples/lorawan-example.cc:94

Best regards
Eryk Schiller

**Comment by OniremE** [comment]
Same error here :(
